name: Firebase Hosting Deploy
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: '${{ github.ref }}'
      - name: Sapper export
        run: 'npm install && npm run export'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
